name: Say Hello!
description: Say Hello and record the time
author: Melinda

# Define your inputs here.
inputs:
  who-to-greet:
    description: "Who should we say Hello"
    default: "World"

# Define your outputs here.
outputs:
  time:
    description: "The time we say Hello"

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{inputs.who-to-greet}}  
